// ingredient_list.dart

Future<List<String>> fetchIngredients() async {
  await Future.delayed(Duration(seconds: 2)); // Simulate network delay
  return [
    'Tomato', 'Onion', 'Garlic', 'Bell Pepper', 'Chicken', 'Broccoli',
    'Spinach', 'Carrot', 'Mushroom', 'Potato', 'Ginger', 'Cilantro', 'Mint',
    'Curry Leaves', 'Green Chilies', 'Red Chilies', 'Turmeric', 'Cumin',
    'Coriander', 'Fenugreek', 'Asafoetida', 'Mustard Seeds', 'Fennel Seeds',
    'Cardamom', 'Cinnamon', 'Cloves', 'Bay Leaves', 'Black Pepper', 'Salt',
    'Sugar', 'Garam Masala', 'Paneer', 'Yogurt', 'Lemon', 'Lime', 'Rice',
    'Basmati Rice', 'Brown Rice', 'Wheat Flour', 'Chickpea Flour', 'Semolina',
    'Lentils', 'Toor Dal', 'Moong Dal', 'Chana Dal', 'Urad Dal', 'Masoor Dal',
    'Black Beans', 'Kidney Beans', 'Soy Beans', 'Green Peas', 'Cauliflower',
    'Cabbage', 'Eggplant', 'Bitter Gourd', 'Bottle Gourd', 'Drumstick', 'Okra',
    'Pumpkin', 'Zucchini', 'Radish', 'Beetroot', 'Sweet Potato', 'Taro Root',
    'Yam', 'Fenugreek Leaves', 'Curry Powder', 'Chili Powder', 'Paprika',
    'Coconut', 'Coconut Milk', 'Coconut Oil', 'Ghee', 'Butter', 'Milk', 'Cream',
    'Buttermilk', 'Cheese', 'Eggs', 'Fish', 'Prawns', 'Crab', 'Lobster', 'Mutton',
    'Beef', 'Pork', 'Duck', 'Turkey', 'Quail', 'Saffron', 'Rose Water', 'Kewra Water',
    'Dry Fruits', 'Almonds', 'Cashews', 'Raisins', 'Pistachios', 'Dates', 'Figs',
    'Walnuts', 'Peanuts', 'Sesame Seeds', 'Sunflower Seeds', 'Poppy Seeds',
    'Chia Seeds', 'Basil Seeds', 'Tamarind', 'Jaggery', 'Honey', 'Molasses',
    'Apple', 'Banana', 'Mango', 'Papaya', 'Pineapple', 'Guava', 'Lychee',
    'Pomegranate', 'Watermelon', 'Cantaloupe', 'Grapes', 'Oranges', 'Tangerines',
    'Apples', 'Pears', 'Peaches', 'Plums', 'Cherries', 'Strawberries', 'Raspberries',
    'Blueberries', 'Blackberries', 'Kiwi', 'Dragon Fruit', 'Passion Fruit', 'Avocado',
    'Cucumber', 'Lettuce', 'Celery', 'Bell Peppers', 'Jalapenos', 'Habaneros',
    'Squash', 'Artichoke', 'Asparagus', 'Bamboo Shoots', 'Brussels Sprouts',
    'Collard Greens', 'Kale', 'Swiss Chard', 'Turnip', 'Parsnip', 'Horseradish',
    'Leeks', 'Scallions', 'Shallots', 'Watercress', 'Endive', 'Arugula', 'Radicchio',
    'Bean Sprouts', 'Snow Peas', 'Snap Peas', 'Green Beans', 'Wax Beans', 'Navy Beans',
    'Lima Beans', 'Butter Beans', 'Adzuki Beans', 'Cannellini Beans', 'Black-Eyed Peas',
    'Split Peas', 'Chickpeas', 'Barley', 'Oats', 'Quinoa', 'Millet', 'Sorghum', 'Teff',
    'Buckwheat', 'Amaranth', 'Rye', 'Spelt', 'Kamut', 'Farro', 'Bulgur', 'Freekeh', 'Orzo',
    'Couscous', 'Polenta', 'Cornmeal', 'Rice Flour', 'Corn Flour', 'Almond Flour',
    'Coconut Flour', 'Oat Flour', 'Tapioca Flour', 'Arrowroot Flour', 'Potato Starch',
    'Cornstarch', 'Gelatin', 'Agar Agar', 'Xanthan Gum', 'Guar Gum', 'Pectin', 'Baking Soda',
    'Baking Powder', 'Yeast', 'Bread', 'Pasta', 'Noodles', 'Vermicelli', 'Spaghetti',
    'Macaroni', 'Linguine', 'Fettuccine', 'Lasagna', 'Tortellini', 'Ravioli', 'Gnocchi',
    'Udon', 'Soba', 'Ramen', 'Rice Noodles', 'Glass Noodles', 'Spring Roll Wrappers',
    'Wonton Wrappers', 'Phyllo Dough', 'Puff Pastry', 'Shortcrust Pastry', 'Pie Crust',
    'Pizza Dough', 'Tortillas', 'Pita Bread', 'Naan', 'Roti', 'Paratha', 'Chapati', 'Bhatura',
    'Dosa', 'Idli', 'Vada', 'Samosa', 'Pakora', 'Chutney', 'Pickles', 'Sauerkraut', 'Kimchi',
    'Miso', 'Soy Sauce', 'Tamari', 'Teriyaki Sauce', 'Sriracha', 'Hot Sauce', 'BBQ Sauce',
    'Ketchup', 'Mustard', 'Mayonnaise', 'Vinegar', 'Apple Cider Vinegar', 'Balsamic Vinegar',
    'Rice Vinegar', 'White Vinegar', 'Red Wine Vinegar', 'Lemon Juice', 'Lime Juice',
    'Orange Juice', 'Grapefruit Juice', 'Pineapple Juice', 'Coconut Water', 'Almond Milk',
    'Soy Milk', 'Rice Milk', 'Oat Milk', 'Hemp Milk', 'Cashew Milk', 'Macadamia Milk',
    'Cocoa Powder', 'Carob Powder', 'Dark Chocolate', 'Milk Chocolate', 'White Chocolate',
    'Coconut Sugar', 'Maple Syrup', 'Agave Syrup', 'Brown Sugar', 'Powdered Sugar',
    'Vanilla Extract', 'Almond Extract', 'Lemon Extract', 'Orange Extract', 'Peppermint Extract',
    'Rosemary', 'Thyme', 'Basil', 'Oregano', 'Parsley', 'Dill', 'Sage', 'Tarragon', 'Chives',
    'Marjoram', 'Bay Leaf', 'Safflower', 'Lemongrass', 'Galangal', 'Kaffir Lime Leaves',
    'Pandan Leaves', 'Saffron', 'Sumac', 'Za''atar', 'Harissa', 'Ras el Hanout', 'Berbere',
    'Shichimi Togarashi', 'Chinese Five Spice', 'Cajun Spice', 'Creole Spice', 'Italian Seasoning',
    'Herbes de Provence', 'Taco Seasoning', 'Ranch Seasoning', 'Fajita Seasoning', 'Gochujang',
    'Miso Paste', 'Tahini', 'Peanut Butter', 'Almond Butter', 'Cashew Butter', 'Sunflower Seed Butter',
    'Pumpkin Seed Butter', 'Hummus', 'Baba Ganoush', 'Guacamole', 'Salsa', 'Pesto', 'Tapenade',
    'Chimichurri', 'Aioli', 'Tzatziki', 'Raita', 'Yogurt Sauce', 'Curry Sauce', 'Tomato Sauce',
    'Marinara Sauce', 'Alfredo Sauce', 'Pasta Sauce', 'Pizza Sauce', 'Gravy', 'Broth', 'Stock',
  ];
}
